vn_spec: "Quy chuẩn kỹ thuật quốc gia do Bộ TT&TT ban hành"
vn_laws: "Luật số 24/2023/QH15 của Quốc hội - Luật Viễn thông"
ieee_spec: "Tiêu chuẩn kỹ thuật của IEEE"
itu_spec: "Khuyến nghị kỹ thuật của ITU-T/ITU-R"
3gpp_spec: "Tiêu chuẩn di động của 3GPP"
arxiv: "ArXiv"
